#!/bin/bash

temp=$(mktemp)

while true
do
vms=$(vboxmanage list vms | sed -r '/^["]/!d; s/"([^"]*)"/\1/')
runningvms=$(vboxmanage list runningvms | sed -r '/^["]/!d; s/"([^"]*)"/\1/')
while read vm
do

dialog --menu "Available VMs:" 0 0 0 $(vboxmanage list vms | sed -r '/^["]/!d; s/"([^"]*)"/\1/') 2> $temp

if [ $? -eq 1 ]
then
	exit
fi

vm=$(cat $temp)

if vboxmanage list runningvms | grep -q "$vm"
then
	dialog --menu "Operation:" 0 0 0 pause "Pause the VM" resume "Resume the VM" savestate "Save the VM and unload it" poweroff "Pull the plug on the VM" 2> $temp

	if [ $? -eq 1 ]
	then
		exit
	fi
#	vboxmanage controlvm "$vm" "$(cat $temp)" | dialog --programbox 0 0
	#vboxmanage controlvm "$vm" "$(cat $temp)" > $temp &

	#dialog --tailbox $temp 20 60 
	#vboxmanage controlvm "$vm" "$(cat $temp)"
	vboxmanage controlvm "$vm" "$(cat $temp)" && sleep 1 && dialog --msgbox "Operation on $vm was successful!" 10 60
#	read
sleep 1
else
	dialog --yesno "Start $vm?" 0 0
	if [ $? -eq 0 ]
	then
		if [ -n "$DISPLAY" ]
		then
			type=gui
		else
			type=headless
		fi
		#vboxmanage startvm "$vm" --type $type > $temp
		#dialog --tailbox $temp 20 60
		#vboxmanage startvm "$vm" --type $type
		vboxmanage startvm "$vm" --type $type && sleep 1 && dialog --msgbox "Operation on $vm was successful!" 10 60
#		read

sleep 1
	fi
fi

done
